language: python
python:
- 3.5
install:
- pip install sphinx sphinx_rtd_theme
script: sphinx-build -nvWEab html . docs
after_success:
- "./update.sh"
env:
  global:
    secure: Mqg5/2d6C+irBqZpZzUIILUT3j8/LOhBeX8ZWMrYkruuESVussdM/LbzSSwoY0PLTLo/6kmVsgephOtzKZ5JYxSKjteZIOJzrFI6FdypnHJ/WKDukjsDwyL9x/xLo3PjSCs5BW7byHKPbCrrOMXPSICo3W7frygxjE5E0y46c2zIn7oXF1+QqD4MSgCWL2gwu8sUun+0SRqVrOjJUDOR9FXU8TsfUkFqNP78WCksC1ANJ7X8O6olLK/0RFgQ6bm/e3JPpOyMXILMhFjoMcn46SW4IFKZoAU+3p2a8W2eFPlicAIXMOPy/ZmOXr/rPj0uW3/P6sLKCMbv3167tADvAM73A7cd9Zske+X2REYuBg7Yz8NhecfPTne4HCnwvyaZ/vgGAfW/Bkq5mZzRmnGvOXNag4HVMbAavP42DSEe5SPF4H1Ge33BuFOYdn3ywuUMCb8ZL+eW+drbuqgWtSkGe0sPtQKQKgR5jivvpMKVWOZwmQNKtp6hqoSm0QvmJuQHrEMlFoh1OdaTfbXDsP786hx8x4TFpkV1uNzIHziEfKXHvcumkempwJrtXt6lduz1WrSrRic/xwbvK8477UQGKapvHJhq1k8yesPXJfb4PKXWxvJtPx0FVqVs8AfME8oH1inwpKeyYv8OOCXs7wUbeUw9+bnq4IMnJz/1P7q6rJs=
